# Generated by Django 5.1.3 on 2024-11-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date was created')),
                ('charClasses', models.JSONField()),
                ('charRaces', models.JSONField()),
                ('charAttributes', models.JSONField()),
                ('charStatuses', models.JSONField()),
                ('charBackground', models.JSONField()),
                ('charWeaponTemplate', models.JSONField()),
                ('charEquipmentTemplate', models.JSONField()),
                ('charConsumableTemplate', models.JSONField()),
                ('charQuestItemTemplate', models.JSONField()),
                ('sheetTemplateOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.JSONField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet_maker_app.sheettemplate')),
            ],
        ),
    ]
