# Generated by Django 5.1.3 on 2024-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
