# Generated by Django 5.1.3 on 2024-11-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0003_rename_charclasses_sheettemplate_charavailableclasses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='sheet',
            new_name='template_instance',
        ),
    ]
