# Generated by Django 5.1.3 on 2024-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0004_rename_sheet_charactersheet_template_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
