# Generated by Django 5.1.3 on 2024-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0007_rename_sheettemplateowner_sheettemplate_sheet_template_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheettemplate',
            old_name='statuses',
            new_name='stats',
        ),
    ]
