# Generated by Django 5.1.3 on 2024-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0008_rename_statuses_sheettemplate_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date was created'),
        ),
    ]
