# Generated by Django 5.1.3 on 2024-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0010_alter_sheettemplate_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheettemplate',
            name='attributes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sheettemplate',
            name='available_classes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sheettemplate',
            name='available_races',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sheettemplate',
            name='background',
            field=models.JSONField(default=list),
        ),
    ]
