# Generated by Django 5.1.3 on 2025-01-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0012_charactersheet_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='template_instance',
            new_name='stats',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='attributes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='background',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='char_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='race',
            field=models.CharField(default='', max_length=200),
        ),
    ]
