# Generated by Django 5.1.3 on 2025-01-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0013_rename_template_instance_charactersheet_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='background',
            field=models.JSONField(default=dict),
        ),
    ]
