# Generated by Django 5.1.3 on 2025-01-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0014_alter_charactersheet_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
