# Generated by Django 5.1.3 on 2025-01-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0016_alter_charactersheet_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
    ]
