# Generated by Django 5.1.3 on 2025-01-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0017_alter_charactersheet_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='inventory',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='consumables',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='equipments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='quest_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='weapons',
            field=models.JSONField(default=list),
        ),
    ]
