# Generated by Django 5.1.3 on 2025-01-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet_maker_app', '0018_remove_charactersheet_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='consumables',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='equipments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='quest_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='weapons',
            field=models.JSONField(default=dict),
        ),
    ]
